---
title: "clustering"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, message=FALSE, error=FALSE}
library(scater)
library(scran)
library(pheatmap)
```

## Import filtered sce object
```{r import object}
sce <- readRDS('sce_filtered.rds')
```


## Select Variable features
```{r}
dec <- modelGeneVar(sce)

# Visualizing the fit:
fit.sce <- metadata(dec)
plot(fit.sce$mean, fit.sce$var, xlab="Mean of log-expression",
    ylab="Variance of log-expression")
curve(fit.sce$trend(x), col="dodgerblue", add=TRUE, lwd=2)

dec[order(dec$bio, decreasing=TRUE),] 

```

## select highly variable genes
```{r}
# Taking the top 2000 genes or top 10%  here:
hvg.sce.var <- getTopHVGs(dec, n=2000)
str(hvg.sce.var)
top10 <- hvg.sce.var[1:10]

plot(fit.sce$mean, fit.sce$var, xlab="Mean of log-expression",
    ylab="Variance of log-expression")
curve(fit.sce$trend(x), col="dodgerblue", add=TRUE, lwd=2)
text(fit.sce$mean[top10], fit.sce$var[top10], labels = names(fit.sce$var[top10]), adj=c(0,1), cex=0.8)


```

##PCA
```{r}
set.seed(100) # See below.
sce <- runPCA(sce, subset_row=hvg.sce.var, name="PCA")
reducedDimNames(sce)
dim(reducedDim(sce, "PCA"))
```

## choose numbers of PCs for subsequent analysis
```{r}
percent.var <- attr(reducedDim(sce, 'PCA'), "percentVar")
plot(percent.var, xlab="PC", ylab="Variance explained (%)")

sum(percent.var[1:20])

#apply number of PCS
reducedDim(sce, "PCA_20") <- reducedDim(sce, "PCA")[,1:20]
ncol(reducedDim(sce, "PCA_20"))

#Visualize PCA
plotReducedDim(sce, dimred="PCA", colour_by="SELL")
plotReducedDim(sce, dimred="PCA", colour_by="CD34")
plotReducedDim(sce, dimred="PCA", ncomponents=4)
```

## Clustering
```{r}
#the higher the k the less clusters
g.major <- buildSNNGraph(sce, k=30, use.dimred = 'PCA_20')
clust.major <- igraph::cluster_infomap(g.major)$membership
table(clust.major)
colLabels(sce) <- factor(clust.major)

plotExpression(sce, features="CD56-TotalA", x="label", colour_by="label")+theme(text = element_text(size = 13), axis.text=element_text(size=13)) +
scale_color_manual(values = c('1' = "#729ece", '2' = "#67bf5c", '3' = "#ad8bc9", '4'='#ed665d', '5'='#a8786e', '6'='#ed97ca', '7'='#ff9e4a', '8'='#a2a2a2'),aesthetics = "fill")
plotExpression(sce, features="CD34-TotalA", x="label", colour_by="label")+theme(text = element_text(size = 13), axis.text=element_text(size=13)) +
scale_color_manual(values = c('1' = "#729ece", '2' = "#67bf5c", '3' = "#ad8bc9", '4'='#ed665d', '5'='#a8786e', '6'='#ed97ca', '7'='#ff9e4a', '8'='#a2a2a2'),aesthetics = "fill")
plotExpression(sce, features="CXCR6-TotalA", x="label", colour_by="label")+theme(text = element_text(size = 13), axis.text=element_text(size=13)) +
scale_color_manual(values = c('1' = "#729ece", '2' = "#67bf5c", '3' = "#ad8bc9", '4'='#ed665d', '5'='#a8786e', '6'='#ed97ca', '7'='#ff9e4a', '8'='#a2a2a2'),aesthetics = "fill")
plotExpression(sce, features="CD117-TotalA", x="label", colour_by="label")+theme(text = element_text(size = 13), axis.text=element_text(size=13)) +
scale_color_manual(values = c('1' = "#729ece", '2' = "#67bf5c", '3' = "#ad8bc9", '4'='#ed665d', '5'='#a8786e', '6'='#ed97ca', '7'='#ff9e4a', '8'='#a2a2a2'),aesthetics = "fill")

ggsave("CXCR6.tiff",plot = last_plot(),device = NULL,path = NULL,scale = 1,width = 7,height = 4, units = c("in", "cm", "mm", "px"),dpi =300,limitsize = TRUE,bg = NULL,)

```

## run umap
```{r}
set.seed(110011001)
sce <- runUMAP(sce, dimred="PCA_20", n_neighbors=30, min_dist=0.6, name='UMAP')

plotReducedDim(sce, "UMAP", text_by='label', colour_by="label")+ theme(text = element_text(size = 13), axis.text=element_text(size=13)) +
scale_color_manual(values = c('1' = "#729ece", '2' = "#67bf5c", '3' = "#ad8bc9", '4'='#ed665d', '5'='#a8786e', '6'='#ed97ca', '7'='#ff9e4a', '8'='#a2a2a2'),aesthetics = "fill")

plotReducedDim(sce, "UMAP", text_by='label', colour_by='CCL3')+ theme(text = element_text(size = 15), axis.text=element_text(size=15))


#export UMAP plot
ggsave("CCL3.tiff",plot = last_plot(),device = NULL,path = NULL,scale = 1,width = 6,height = 5,
  dpi = 300,limitsize = TRUE,bg = NULL,
)
```

## Differential gene expression
```{r}
#ranked by significance
markers_up<- findMarkers(sce, test="wilcox", direction='up', pval.type='any')

cluster1<-as.data.frame(markers_up[[1]])
cluster2<- as.data.frame(markers_up[[2]])
cluster3<- as.data.frame(markers_up[[3]])
cluster4<- as.data.frame(markers_up[[4]])
cluster5<- as.data.frame(markers_up[[5]])
cluster6<- as.data.frame(markers_up[[6]])
cluster7<- as.data.frame(markers_up[[7]])
cluster8<- as.data.frame(markers_up[[8]])

#adjust cluster number to draw an heatmap for each cluster
best.set <- cluster6[cluster6$Top <= 5,]
AUCs <- getMarkerEffects(best.set, "AUC")

#AUC >0.5 is upregulated
pheatmap(AUCs, breaks=seq(0, 1, length.out=101), cellwidth=10, cellheight=10, scale='none', cluster_cols=FALSE, cluster_rows=FALSE)

#heatmap with hierarchical clustering
sce$subset <- sce$label
sce$subset <- gsub('1$', '1. CD56dim GZMK-', sce$subset)
sce$subset <- gsub('2$', '3. ltNK', sce$subset)
sce$subset <- gsub('3$', '5. CD34+', sce$subset)
sce$subset <- gsub('4$', '4. CD56bright', sce$subset)
sce$subset <- gsub('5$', '6. ILC', sce$subset)
sce$subset <- gsub('6$', '7. NKprolif', sce$subset)
sce$subset <- gsub('7$', '2. CD56dimGZMK+', sce$subset)
sce$subset <- gsub('8$', '8. CD56-', sce$subset)

top5=list()
for (i in 1:length(markers_up)){
  top5[[i]] <- rownames(markers_up[[i]])[markers_up[[i]]$Top<=5]
}

plotHeatmap(sce, features=unique(unlist(top5)), colour_columns_by='subset',show_rownames=FALSE, symmetric=FALSE, center=FALSE)
```
## cell cycle stage
```{r}
mm.pairs <- readRDS(system.file("exdata", "human_cycle_markers.rds", package="scran"))
assignments <- cyclone(sce, mm.pairs, gene.names=rowData(sce)$ID)
table(assignments$phases, colLabels(sce))
sce$cellcycle <- assignments$phases
plotReducedDim(sce, dimred="UMAP", colour_by ="cellcycle", point_size=2, text_by = 'label')+theme(text = element_text(size = 15), axis.text=element_text(size=15))

ggsave("Cellcycle.tiff",plot = last_plot(),device = NULL,path = NULL,scale = 1,width = 5,height = 4, units = c("in", "cm", "mm", "px"),dpi =300,limitsize = TRUE,bg = NULL,)
```


##save object
```{r}
saveRDS(sce, 'sce_clustered.rds')
```

## subcluster CD56bright
```{r}
sce.bright <- sce[,sce$label %in% c('4')]

#variable genes
dec.bright<- modelGeneVar(sce.bright)
hvg.sce.var <- getTopHVGs(dec.bright, n=2000)
str(hvg.sce.var)

#PCA
set.seed(100) # See below.
sce.bright <- runPCA(sce.bright, subset_row=hvg.sce.var, name="PCA")
percent.var <- attr(reducedDim(sce.bright), "percentVar")
plot(percent.var, xlab="PC", ylab="Variance explained (%)")
reducedDim(sce.bright, "PCA_20") <- reducedDim(sce.bright, "PCA")[,1:20]

#higher k, less clusters.
g.bright <- buildSNNGraph(sce.bright, k=8, use.dimred="PCA_20")
clust.bright <- igraph::cluster_infomap(g.bright)$membership
sce.bright$label<- factor(clust.bright)

#UMAP
set.seed(110011001)
sce.bright <- runUMAP(sce.bright, dimred="PCA_20", n_neighbors=30, min_dist=0.6, name="UMAP")
plotReducedDim(sce.bright,dimred="UMAP", colour_by ="label", point_size=4, text_by = 'label')

plotReducedDim(sce.bright,dimred="UMAP", colour_by ="CD117-TotalA", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=17))
plotReducedDim(sce.bright,dimred="UMAP", colour_by ="CD27", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=17))
plotReducedDim(sce.bright,dimred="UMAP", colour_by ="FCGR3A", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=15))
plotReducedDim(sce.bright,dimred="UMAP", colour_by ="CCL5", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=15))

ggsave("CCL5_bright.tiff",plot = last_plot(),device = NULL,path = NULL,scale = 1,width = 6,height = 5,dpi = 300,limitsize = TRUE,bg = NULL,)
```

##subcluster ltNK
```{r}
sce.ltnk <- sce[,sce$label %in% c('2')]

#variable genes
dec.ltnk<- modelGeneVar(sce.ltnk)
hvg.sce.var <- getTopHVGs(dec.ltnk, n=2000)
str(hvg.sce.var)

#PCA
set.seed(100) # See below.
sce.ltnk <- runPCA(sce.ltnk, subset_row=hvg.sce.var, name="PCA")
percent.var <- attr(reducedDim(sce.ltnk), "percentVar")
plot(percent.var, xlab="PC", ylab="Variance explained (%)")
reducedDim(sce.ltnk, "PCA_20") <- reducedDim(sce.ltnk, "PCA")[,1:20]

#higher k, less clusters.
g.ltnk <- buildSNNGraph(sce.ltnk, k=8, use.dimred="PCA_20")
clust.ltnk <- igraph::cluster_infomap(g.ltnk)$membership
sce.ltnk$label<- factor(clust.ltnk)

#UMAP
set.seed(110011001)
sce.ltnk <- runUMAP(sce.ltnk, dimred="PCA_20", n_neighbors=30, min_dist=0.6, name="UMAP")
plotReducedDim(sce.ltnk,dimred="UMAP", colour_by ="label", point_size=4, text_by = 'label')

plotReducedDim(sce.ltnk,dimred="UMAP", colour_by ="CD226", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=17))
plotReducedDim(sce.ltnk,dimred="UMAP", colour_by ="KLRC1", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=17))
plotReducedDim(sce.ltnk,dimred="UMAP", colour_by ="FCGR3A", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=15))
plotReducedDim(sce.ltnk,dimred="UMAP", colour_by ="CCL5", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=15))

ggsave("CCL5_ltnk.tiff",plot = last_plot(),device = NULL,path = NULL,scale = 1,width = 6,height = 5,dpi = 300,limitsize = TRUE,bg = NULL,)
```

## subcluster CD56dimGZMK+
```{r}
sce.dimgzmkplus <- sce[,sce$label %in% c('7')]

#variable genes
dec.dimgzmkplus<- modelGeneVar(sce.dimgzmkplus)
hvg.sce.var <- getTopHVGs(dec.dimgzmkplus, n=2000)
str(hvg.sce.var)

#PCA
set.seed(100) # See below.
sce.dimgzmkplus <- runPCA(sce.dimgzmkplus, subset_row=hvg.sce.var, name="PCA")
percent.var <- attr(reducedDim(sce.dimgzmkplus), "percentVar")
plot(percent.var, xlab="PC", ylab="Variance explained (%)")
reducedDim(sce.dimgzmkplus, "PCA_20") <- reducedDim(sce.dimgzmkplus, "PCA")[,1:20]

#higher k, less clusters.
g.dimgzmkplus <- buildSNNGraph(sce.dimgzmkplus, k=8, use.dimred="PCA_20")
clust.dimgzmkplus <- igraph::cluster_infomap(g.dimgzmkplus)$membership
sce.dimgzmkplus$label<- factor(clust.dimgzmkplus)

#UMAP
set.seed(110011001)
sce.dimgzmkplus <- runUMAP(sce.dimgzmkplus, dimred="PCA_20", n_neighbors=30, min_dist=0.6, name="UMAP")
plotReducedDim(sce.dimgzmkplus,dimred="UMAP", colour_by ="label", point_size=4, text_by = 'label')

plotReducedDim(sce.dimgzmkplus,dimred="UMAP", colour_by ="GZMK", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=17))
plotReducedDim(sce.dimgzmkplus,dimred="UMAP", colour_by ="GZMB", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=17))
plotReducedDim(sce.dimgzmkplus,dimred="UMAP", colour_by ="FGFBP2", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=15))
plotReducedDim(sce.dimgzmkplus,dimred="UMAP", colour_by ="CCL5", point_size=6, text_by = 'label')+theme(text = element_text(size = 17), axis.text=element_text(size=15))

ggsave("CCL5_dim.tiff",plot = last_plot(),device = NULL,path = NULL,scale = 1,width = 6,height = 5,dpi = 300,limitsize = TRUE,bg = NULL,)

```

